name: main-issue
description: 親チケット
title: "⭐︎"
labels: ["main"]
body:
  - type: input
    id: refurl
    attributes:
      label: 参考リンク (URL)
      placeholder: https://example.com
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 目的や背景など
  - type: textarea
    id: detail
    attributes:
      label: 詳細 (目的・目標・戦略・戦術)
      value: |
        **目的**:  
        
        **目標**:  
        
        **戦略**:  
        
        **戦術**:  

  - type: textarea
    id: kpi
    attributes:
      label: KPI (いつまでに/どれくらい進捗なら OK?)
      placeholder: |
        例) 2025‑05‑31 までに Issue 消化率 60 % 以上
  - type: textarea
    id: risk
    attributes:
      label: リスク管理 (継続が難しくなったときの対策)
      placeholder: |
        例) 進捗 30 % 未満の場合 → 作業を週 3 セットに増やす