name: Task
description: 個人タスク
title: "[ ] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: "## Goal\n<!-- 完了条件を 1 行で -->"
  - type: textarea
    id: steps
    attributes:
      label: Steps
      value: |
        - [ ] 
  - type: input
    id: due
    attributes:
      label: Due date